### ISSUE TITLE
Is it an overflow bug?

### ISSUE THREAD

**Issue by mustakcsecuet** [unicorn-engine/unicorn#750]
Hi

I got this decoded code from my decoder code:
```
0x00000526:	pushq	%rbp
RIP Value: 0x526
0x00000527:	movq	%rsp, %rbp
RIP Value: 0x527
0x0000052a:	subq	$0x10, %rsp
RIP Value: 0x52a
0x0000052e:	leaq	-8(%rbp), %rdx
RIP Value: 0x52e
0x00000532:	leaq	-4(%rbp), %rax
RIP Value: 0x532
0x00000536:	movq	%rax, %rsi
RIP Value: 0x536
0x00000539:	movl	$0x400604, %edi
RIP Value: 0x539
0x0000053e:	movl	$0, %eax
RIP Value: 0x53e
0x00000543:	callq	0x420
RIP Value: 0x543
0x00000420:	jmpq	*0x20055a(%rip)
RIP Value: 0x420
0x00000000:	jg	0x47
RIP Value: 0x0

```
I am not sure why unicorn emulator suddenly jump to `0x00000000` instead of `0x200980`?
I have read a complete binary and try to emulate it, I have written the code starting from `0x000000` but start emulation from `0x526` which is actually the main function entry point. Everything goes fine until that point [`0x00000420`], is there any overflow issue in the code or something I am missing?
I have used page size as `4*1024*1024` which I guess enough.

**Comment by Nukem9** [comment]
If I'm reading this correctly....`jmpq	*0x20055a(%rip)` is `jmp qword ptr [rip + 0x20055A]` in intel syntax. The pointer at `[rip + 0x20055A]` is probably 0.

**Comment by mustakcsecuet** [comment]
It's a part of complete code where `callq 0x420 is <__isoc99_scanf@@GLIBC_2.7>`
The jump after that should go some address 0x200980.
The same code with valgrind trace shows following:
```
0x00400526: 55                                            pushq  %rbp < main function execution starts here >
   def_mem: 0xffefffc60 (8)
   use_mem: 
   def_reg: rsp
   use_reg: rbp, rsp
0x00400527: 48 89 e5                                      movq  %rsp, %rbp 
   def_mem: 
   use_mem: 
   def_reg: rbp
   use_reg: rsp
0x0040052a: 48 83 ec 10                                   subq  $0x10, %rsp 
   def_mem: 
   use_mem: 
   def_reg: cc_op, cc_dep1, cc_dep2, rsp
   use_reg: rsp
0x0040052e: 48 8d 55 f8                                   leaq  -8(%rbp), %rdx 
   def_mem: 
   use_mem: 
   def_reg: rdx
   use_reg: rbp
0x00400532: 48 8d 45 fc                                   leaq  -4(%rbp), %rax 
   def_mem: 
   use_mem: 
   def_reg: rax
   use_reg: rbp
0x00400536: 48 89 c6                                      movq  %rax, %rsi 
   def_mem: 
   use_mem: 
   def_reg: rsi
   use_reg: rax
0x00400539: bf 04 06 40 00                                movl  $0x400604, %edi 
   def_mem: 
   use_mem: 
   def_reg: rdi
   use_reg: 
0x0040053e: b8 00 00 00 00                                movl  $0, %eax 
   def_mem: 
   use_mem: 
   def_reg: rax
   use_reg: 
0x00400543: e8 d8 fe ff ff                                callq  0x400420 <__isoc99_scanf@@GLIBC_2.7>
   def_mem: 0xffefffc48 (8)
   use_mem: 
   def_reg: rsp
   use_reg: rsp
0x00400420: ff 25 5a 05 20 00                             jmpq  *0x20055a(%rip) 
   def_mem: 
   use_mem: 0x00600980 (8)
   def_reg: rip
   use_reg: 
```
where `0x00600980` is the offset of `__isoc99_scanf@GLIBC_2.7 + 0`
This is what I have from readelf:
```
Relocation section '.rela.plt' at offset 0x388 contains 3 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000600970  000100000007 R_X86_64_JUMP_SLO 0000000000000000 puts@GLIBC_2.2.5 + 0
000000600978  000200000007 R_X86_64_JUMP_SLO 0000000000000000 __libc_start_main@GLIBC_2.2.5 + 0
000000600980  000400000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc99_scanf@GLIBC_2.7 + 0
```
I am sure what I got from unicorn is not the expected trace, so in such case what should I have to do to turn it working as expected? Any suggestion?
